#!/bin/bash

green="\e[0;32m\033[1m"
end="\033[0m\e[0m"
red="\e[0;31m\033[1m"
blue="\e[0;34m\033[1m"
yellow="\e[0;33m\033[1m"
purple="\e[0;35m\033[1m"
turquoise="\e[0;36m\033[1m"
gray="\e[0;37m\033[1m"

function banner(){

	clear

	echo -e "${red}"

	echo " █████╗ ██╗   ██╗████████╗ ██████╗  █████╗ ██╗    ██╗███████╗███████╗ ██████╗ ███╗   ███╗███████╗"
	echo "██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗██╔══██╗██║    ██║██╔════╝██╔════╝██╔═══██╗████╗ ████║██╔════╝"
	echo "███████║██║   ██║   ██║   ██║   ██║███████║██║ █╗ ██║█████╗  ███████╗██║   ██║██╔████╔██║█████╗  "
	echo "██╔══██║██║   ██║   ██║   ██║   ██║██╔══██║██║███╗██║██╔══╝  ╚════██║██║   ██║██║╚██╔╝██║██╔══╝  "
	echo "██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║  ██║╚███╔███╔╝███████╗███████║╚██████╔╝██║ ╚═╝ ██║███████╗"
	echo "╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝  ╚═╝ ╚══╝╚══╝ ╚══════╝╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝"

}

function menu(){

	banner

	echo -e "${blue}"

	sleep 0.25
	echo
	echo "1 -> Instalar dependencias"
	sleep 0.25
	echo
	echo "2 -> Instalar Awesome"
	sleep 0.25
	echo
	echo "3 -> Instalar widgets de Awesome"
	sleep 0.25
	echo
	echo "4 -> Instalar tema de Awesome"
	sleep 0.25
	echo
	echo "5 -> Instalar elementos adicionales: rofi, caja, firefox..."
	sleep 0.25
	echo
	echo "6 -> Instalar todo"
	sleep 0.25
	echo
	echo "7 -> Salir"
	sleep 0.25

	echo
	read -p "--> " comando

	if [ "$comando" == "1" ]; then
		dependencias
		fi

        if [ "$comando" == "2" ]; then
                build
                fi

        if [ "$comando" == "3" ]; then
                awesome
                fi

        if [ "$comando" == "4" ]; then
                themes
                fi

        if [ "$comando" == "5" ]; then
                tools
                fi

        if [ "$comando" == "6" ]; then
                dependencias
		build
		awesome
		themes
		tools
                fi
}

function dependencias(){

echo -e "${red}[!] ${yellow}Instalando Dependencias..."


echo -e "${green}[!] ${blue}Dependencias Instaladas."

}

function build(){

echo -e "${red}[!] ${yellow}Instalando Awesome..."


echo -e "${green}[!] ${blue}Awesome Instalado."

}

function awesome(){

echo -e "${red}[!] ${yellow}Instalando temas de Awesome..."


echo -e "${green}[!] ${blue}Los temas de Awesome se han instalado."

}

function themes(){

echo -e "${red}[!] ${yellow}Instalando Widgets de Awesome..."


echo -e "${green}[!] ${blue}Widgets Instalados."

}

function tools(){

echo -e "${red}[!] ${yellow}Instalando funciones extra..."


echo -e "${green}[!] ${blue}Functiones extra Instaladas."

}

username=$(whoami)

if [ "$(id -u)" == "0" ]; then
	echo -e "\n${red}[!] No hay que ser root para ejecutar la herramienta${end}"
	echo
	exit 1
else
	menu
fi
